- name: Install packages using apt
  apt:
    name:
      - snapd
    update_cache: true

- name: Install packages using snap
  community.general.snap:
    name:
      - microk8s
    classic: true

- name: Enable iscsid for openebs
  ansible.builtin.systemd_service:
    name: iscsid
    state: started
    enabled: true
