apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-knative
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/i544c-me/buicha-social-on-sakura
    path: knative
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
