apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: vrc@i544c.me
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-private-key
  solvers:
    - dns01:
        cloudflare:
          email: r.sato7690@me.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-i544c-me
  namespace: argocd
spec:
  secretName: lets-encrypt-private-key
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
    - k8s.i544c.me
    - "*.k8s.i544c.me"
