apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.9.3
    helm:
      values: |
        githubConfigUrl: https://github.com/i544c-me/playground-actions
        githubConfigSecret: github-secret
        controllerServiceAccount:
          name: actions-runner-controller-gha-rs-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  #syncPolicy:
  #  syncOptions:
  #  - ServerSideApply=true # metadata.annotations: Too long: must have at most 262144 bytes を避けるため
