apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: k8s.i544c.me
      http:
        paths:
          - path: /nginx/
            pathType: Prefix
            backend:
              service:
                name: sandbox-nginx
                port:
                  number: 80
  tls:
    - hosts:
      - k8s.i544c.me
      secretName: lets-encrypt-private-key-k8s
