apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-openfaas
  namespace: openfaas
spec:
  ingressClassName: nginx
  rules:
    - host: openfaas.k8s.i544c.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: http
  tls:
    - hosts:
      - openfaas.k8s.i544c.me
      secretName: k8s-i544c-me-secret
